print("Welcome to the tip calculator! ")
bill=input("What was the total bill? $")
tip=input("How much tip would you like to give? 10, 12 or 15? ")
people=input("How many people to split the bill? ")
print(bill)
print(tip)
print(people)

bill=int(tip)/100+int(bill)
result=int(bill)/int(people)
result="{:.2f}".format(result)
print(f"Each person should pay ${result}")